In [18]:
from collections import Counter
import numpy as np

Arr = np.array([[3, 0] for x in range(10)])

Arr2 = np.array([[1,0] for x in range(10)])

Arr = np.append(Arr, Arr2, axis=0)

print(Arr)

cc = Counter(Arr[:,0])

cc

[[3 0]
 [3 0]
 [3 0]
 [3 0]
 [3 0]
 [3 0]
 [3 0]
 [3 0]
 [3 0]
 [3 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]]


Counter({3: 10, 1: 10})

In [26]:
test = np.array(['j' for i in range(10)])

test.astype(np.str_)

array(['j', 'j', 'j', 'j', 'j', 'j', 'j', 'j', 'j', 'j'], dtype='<U1')

In [5]:
import numpy as np
a = np.random.randn(100, 2)/5 + [2,1]
b = np.random.randn(100, 2)/5 + [1,2]
dim = a.shape[-1]
print(a.shape)

a_div, b_div = a - np.mean(a, axis=0), b - np.mean(b, axis=0)
print(np.mean(a, axis=0))
a_mul = np.matmul(a_div.T, a_div) + np.matmul(b_div.T, b_div)
print(np.matmul(a_div.T, a_div))
a_mul

(100, 2)
[2.04565023 0.96301524]
[[ 3.84185837 -0.46072691]
 [-0.46072691  4.60405992]]


array([[ 8.24764606, -0.06193135],
       [-0.06193135,  7.66325788]])

In [8]:
import numpy as np
a = np.array([1,2,3])
b = np.array([[1,2,3], [1,2,4]])

b - a

c = np.array([[2,3,4]])
print(a.shape, c.shape)
a - c

(3,) (1, 3)


array([[-1, -1, -1]])

In [1]:
import numpy as np

a = np.array([3,4,5])

1 / a

array([0.33333333, 0.25      , 0.2       ])

In [7]:
list=['bilibili','maller','maeer','asong','hjsds','gdsds','dfgsds','rysfsd','malles']

list = [l for l in list if 'ma' not in l]
list

['bilibili', 'asong', 'hjsds', 'gdsds', 'dfgsds', 'rysfsd']

In [14]:
import numpy as np
a = np.expand_dims(np.arange(4), -1)
b = np.arange(8).reshape((2,4))
print(a.shape, b.shape)
print(a, '\n\n', b.T)
# np.multiply(a,b.T)
a * b.T

(4, 1) (2, 4)
[[0]
 [1]
 [2]
 [3]] 

 [[0 4]
 [1 5]
 [2 6]
 [3 7]]


array([[ 0,  0],
       [ 1,  5],
       [ 4, 12],
       [ 9, 21]])

In [4]:
import numpy as np
a = (3,1,2,3)
a[0:2]

for i, j in zip(range(3), range(2)):
    print(f'({i}, {j})')

(0, 0)
(1, 1)
